name: inichain

services:
  node1:
    image: ghcr.io/veiurt/arety:latest
    restart: unless-stopped
    cpuset: '${CPU_SET}'
    environment:
      - ETH_ADRRDESS=${ETH_ADRRDESS}
      - WORK_NAME=${WORK_NAME}_1
      - POOL=${POOL}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 2048m
